{{- if .Values.eventHub }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "broadcaster.fullname" . }}-eventhub
  labels:
    app: {{ template "routerlicious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.broadcaster.name }}-eventhub"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.broadcaster.replicas }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/prague-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "routerlicious.name" . }}
        component: "{{ .Values.broadcaster.name }}-eventhub"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "broadcaster.fullname" . }}-eventhub
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
          - 'node'
          - 'dist/event-hub-service/index.js'
          - 'broadcaster'
          - '/usr/src/server/packages/server/routerlicious/dist/broadcaster/index.js'
        env:
        - name: DEBUG
          value: "prague:*"
        - name: NODE_ENV
          value: production
        volumeMounts:
        - name: config
          mountPath: /usr/src/server/packages/server/routerlicious/config/config.json
          subPath: config.json
      dnsConfig:
        options:
        - name: single-request-reopen
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: {{ template "routerlicious.fullname" . }}
{{- end }}