## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: IfNotPresent

historian:
  name: historian
  image: fluidcr.azurecr.io/build/fluidframework/routerlicious/historian:latest
  redis:
    url: redis_url
    port: 6379
    tls: false
  redisForThrottling:
    url: redis_url
    port: 6379
    tls: false
  host: historian_host
  cert: historian_cert
  ingressClass: ingress_class
  riddler: riddler_url
  storageUrl: historian_storage_url
  error:
    track: true
    endpoint: "error_tracking_endpoint"
  throttling:
    maxRequestsPerMs: 1000000
    maxRequestBurst: 1000000
    minCooldownIntervalInMs: 1000000
    minThrottleIntervalInMs: 1000000
  restGitService:
    disableGitCache: false

gitrest:
  name: gitrest
  image: fluidcr.azurecr.io/build/fluidframework/routerlicious/gitrest:latest
  mode: latest
  persistence:
    storageClass: managed-premium
    size: 4094Gi
    accessMode: ReadWriteOnce
  git:
    lib:
      name: nodegit
    persistLatestFullSummary: false

gitssh:
  name: gitssh
  image: fluidcr.azurecr.io/build/fluidframework/routerlicious/gitssh:latest
