## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: IfNotPresent

historian:
  name: historian
  image: fluidcr.azurecr.io/build/fluidframework/routerlicious/historian:latest
  redis:
    url: redis_url
    port: 6379
    tls: false
  host: historian_host
  cert: historian_cert
  ingressClass: ingress_class
  riddler: riddler_url

gitrest:
  name: gitrest
  image: fluidcr.azurecr.io/build/fluidframework/routerlicious/gitrest:latest
  mode: latest
  persistence:
    storageClass: managed-premium
    size: 4094Gi
    accessMode: ReadWriteOnce

gitssh:
  name: gitssh
  image: fluidcr.azurecr.io/build/fluidframework/routerlicious/gitssh:latest

cobalt:
  name: cobalt
  image: prague.azurecr.io/cobalt:1544
  mode: latest
  persistence:
    storageClass: managed-premium
    size: 128Gi
    accessMode: ReadWriteOnce
