replicaCount: 1
image: prague.azurecr.io/gateway:18309

imagePullPolicy: IfNotPresent

name: gateway

alfred:
  externalUrl: alfred_external_url
  tenants:
  - id: fluid
    key: 
  - id: prague
    key:
  - id: github
    key:
  - id: cobalt
    key:
  - id: local
    key:
  url: alfred_internal_url
  key: jwt_key

login:
  microsoft:
    clientId: ""
    secret: ""
  accounts:
    username: ""
    password: ""
  linkedAccounts: {}

gateway:
  externalUrl: gateway_external_url
  host: gateway_host
  cert: gateway_cert
  keyValueUrl: optional_key_value_url

packageManager:
  endpoint: ""
  username: ""
  password: ""

historian:
  externalUrl: historian_external_url
  internalUrl: historian_internal_url

mongodb:
  url: mongodb_url

redis:
  url: pesky-cat-redis
  port: 6379
  tls: false

riddler:
  url: riddler_url

ingress:
  class: ingress_class

error:
  track: false
  endpoint: ""

worker:
  intelligence:
    textAnalytics:
      key: ""
    translation:
      key: ""
  clusterNpm: ""
  npm: ""


express:
  session:
    secret: ""
