apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "historian.fullname" . }}
  labels:
    app: {{ template "historian.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.historian.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.historian.ingressClass }}
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/client-max-body-size: "100m"
    ingress.kubernetes.io/proxy-body-size: "100m"
spec:
 tls:
 - hosts:
   - {{ .Values.historian.host }}
   secretName: {{ .Values.historian.cert }}
 rules:
 - host: {{ .Values.historian.host }}
   http:
     paths:
     - path: /
       pathType: ImplementationSpecific
       backend:
         service:
           name: {{ template "historian.fullname" . }}
           port:
             number: 80
