apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": true,
            "level": "info",
            "timestamp": false,
            "label": "winston"
        },
        "gateway": {
            "maxMessageSize": "16KB",
            "restJsonSize": "50mb",
            "key": "{{ .Values.alfred.key }}",
            "url": "{{ .Values.gateway.externalUrl }}",
            "tenants": [
                {{- $lastIndex := sub (len .Values.alfred.tenants) 1}}
                {{- range $index, $tenant := .Values.alfred.tenants }}
                {{ toJson . }}{{- if ne $index $lastIndex -}}, {{ end }}
                {{- end }}
            ],
            "federation": {
                "endpoints": [
                    "https://www.wu2-ppe.prague.office-int.com",
                    "https://www.wu2.prague.office-int.com",
                    "https://www.eu2.prague.office-int.com",
                    "https://www.we.prague.office-int.com"
                ]
            },
            "auth": {
                "endpoint": "{{ .Values.riddler.url }}"
            }
        },
        "mongo": {
            "endpoint": "{{ .Values.mongodb.url }}",
            "collectionNames": {
                "accounts": "accounts"
            }
        },
        "login": {
            "enabled": true,
            "microsoft": {
                "clientId": "{{ .Values.login.microsoft.clientId }}",
                "secret": "{{ .Values.login.microsoft.secret }}"
            },
            "linkedAccounts": {{ toJson .Values.login.linkedAccounts }},
            "accounts": [
                {
                    "username": "{{ .Values.login.accounts.username }}",
                    "password": "{{ .Values.login.accounts.password }}"
                }
            ]
        },
        "redis": {
            "host": "{{ .Values.redis.url }}",
            "port": "{{ .Values.redis.port }}",
            "tls": {{ .Values.redis.tls }},
            "pass": "{{ .Values.redis.password }}"
        },
        "error": {
            "track": {{ .Values.error.track }},
            "endpoint": "{{ .Values.error.endpoint }}"
        },
        "worker": {
            "intelligence": {
                "textAnalytics": {
                    "key": "{{ .Values.worker.intelligence.textAnalytics.key }}"
                },
                "translation": {
                    "key": "{{ .Values.worker.intelligence.translation.key }}"
                }
            },
            "alfredUrl": "{{ .Values.alfred.url }}",
            "gatewayUrl": "http://{{ template "fullname" . }}",
            "serverUrl": "{{ .Values.alfred.externalUrl }}",
            "blobStorageUrl": "{{ .Values.historian.externalUrl }}",
            "internalBlobStorageUrl": "{{ .Values.historian.internalUrl }}",
            "repository": "FluidFramework",
            "clusterNpm": "{{ .Values.worker.clusterNpm }}",
            "npm": "{{ .Values.worker.npm }}",
            "packageManager": {
                "endpoint": "{{ .Values.packageManager.endpoint }}",
                "username": "{{ .Values.packageManager.username }}",
                "password": "{{ .Values.packageManager.password }}"
            },
            "permission": ["snapshot", "spell", "intel", "translation", "search", "chain-snapshot", "chain-spell", "chain-intel", "chain-translation", "chain-search"]
        },
        "keyValue": {
            "documentUrl": "{{ .Values.gateway.keyValueUrl }}",
            "load": false
        },
        "express": {
            "session": {
                "secret": "{{ .Values.express.session.secret }}"
            }
        }
    }
