services:
  proxy:
    platform: linux/amd64
    image: nginx:latest
    depends_on:
      alfred:
        condition: service_healthy
      historian:
        condition: service_healthy
      nexus:
        condition: service_healthy
    volumes:
      - ./routerlicious/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3003:3003"
      - "3002:3002"
      - "3001:3001"
  alfred:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/server:${ALFRED_IMAGE_TAG:-latest}
    expose:
      - "3000"
    command: node packages/routerlicious/dist/alfred/www.js
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz/startup", "--max-time", "3"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
  nexus:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/server:${ALFRED_IMAGE_TAG:-latest}
    expose:
      - "3000"
    command: node packages/routerlicious/dist/nexus/www.js
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz/ping", "--max-time", "3"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
  deli:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/server:${ALFRED_IMAGE_TAG:-latest}
    command: node packages/routerlicious/dist/kafka-service/index.js deli /usr/src/server/packages/routerlicious/dist/deli/index.js
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    restart: always
  scriptorium:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/server:${ALFRED_IMAGE_TAG:-latest}
    command: node packages/routerlicious/dist/kafka-service/index.js scriptorium /usr/src/server/packages/routerlicious/dist/scriptorium/index.js
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    restart: always
  copier:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/server:${ALFRED_IMAGE_TAG:-latest}
    command: node packages/routerlicious/dist/kafka-service/index.js copier /usr/src/server/packages/routerlicious/dist/copier/index.js
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    restart: always
  scribe:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/server:${ALFRED_IMAGE_TAG:-latest}
    command: node packages/routerlicious/dist/kafka-service/index.js scribe /usr/src/server/packages/routerlicious/dist/scribe/index.js
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    restart: always
  riddler:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/server:${ALFRED_IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    command: node packages/routerlicious/dist/riddler/www.js
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    restart: always
  historian:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/historian:${HISTORIAN_IMAGE_TAG:-latest}
    expose:
      - "3000"
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz/startup", "--max-time", "3"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
  gitrest:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/gitrest:${GITREST_IMAGE_TAG:-latest}
    environment:
      - DEBUG=fluid:*
      - NODE_ENV=development
      - IS_FLUID_SERVER=true
    volumes:
      - git:/home/node/documents
    restart: always
  git:
    image: ${REGISTRY_URL:-mcr.microsoft.com}/fluidframework/routerlicious/gitssh:${GITSSH_IMAGE_TAG:-latest}
    ports:
      - "3022:22"
    volumes:
      - git:/home/git
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "deltas:8:1,rawdeltas:8:1,testtopic:8:1,deltas2:8:1,rawdeltas2:8:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always
  redis:
    image: "redis:alpine"
  mongodb:
    image: "mongo:4"
volumes:
  git:
    driver: local
