version: '3'
services:
    historian:
        build: .
        ports:
            - 3000:3000
            - 5858:5858
        command: node --inspect=0.0.0.0:5858 dist/www.js
        restart: always
    gitrest:
        image: prague.azurecr.io/gitrest:1038
        restart: always
    cobalt:
        image: prague.azurecr.io/cobalt:1544
        restart: always
    redis:
        image: redis:alpine
    mongodb:
        image: mongo:3.4.3
    riddler:
        image: prague.azurecr.io/prague:2302
        command: node dist/riddler/www.js
        environment:
            - DEBUG=routerlicious:*
        restart: always
