version: '3'
services:
    gateway:
        volumes:
            - .:/usr/src/server
    alfred:
        volumes:
            - .:/usr/src/server
    deli:
        volumes:
            - .:/usr/src/server
    scriptorium:
        volumes:
            - .:/usr/src/server
    broadcaster:
        volumes:
            - .:/usr/src/server
    foreman:
        volumes:
            - .:/usr/src/server
    paparazzi:
        volumes:
            - .:/usr/src/server
    routemaster:
        volumes:
            - .:/usr/src/server
    riddler:
        volumes:
            - .:/usr/src/server
