apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "jarvis.fullname" . }}
  labels:
    app: {{ template "routerlicious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.jarvis.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.jarvis.replicas }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fluid-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "routerlicious.name" . }}
        component: "{{ .Values.jarvis.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "jarvis.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
          - 'node'
          - 'deli/dist/jarvis/www.js'
        ports:
        - name: ui
          containerPort: 3000
        env:
        - name: DEBUG
          value: "fluid:*"
        - name: NODE_ENV
          value: "production"
        - name: IS_FLUID_SERVER
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /usr/src/server/functions/deli/config.json
          subPath: config.json
      dnsConfig:
        options:
        - name: single-request-reopen
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: {{ template "routerlicious.fullname" . }}
