apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "metrics.fullname" . }}
  labels:
    app: {{ template "metrics.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    app: {{ template "metrics.fullname" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/metrics-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "metrics.fullname" . }}
        component: "{{ .Values.name }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "metrics.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: DEBUG
          value: "routerlicious:*"
        - name: NODE_ENV
          value: "production"
        - name: IS_FLUID_SERVER
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /home/node/server/config.json
          subPath: config.json
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config
          configMap:
            name: {{ template "metrics.fullname" . }}
