version: '3.4'
services:
    historian:
        build:
          context: .
          target: runner
        ports:
            - 3001:3000
        environment:
            - DEBUG=fluid:*
            - NODE_ENV=development
            - IS_FLUID_SERVER=true
        restart: always
    gitrest:
        image: prague.azurecr.io/gitrest:1038
        restart: always
    redis:
        image: redis:alpine
    mongodb:
        image: mongo:3.4.3
    riddler:
        image: prague.azurecr.io/prague:2302
        command: node dist/riddler/www.js
        environment:
            - DEBUG=routerlicious:*
        restart: always
