apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "routerlicious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": true,
            "level": "info",
            "timestamp": false,
            "label": "winston"
        },
        "gateway": {
            "maxMessageSize": "16KB",
            "restJsonSize": "50mb",
            "key": "{{ .Values.alfred.key }}",
            "url": "{{ .Values.gateway.externalUrl }}",
            "tenants": [
                {{- $lastIndex := sub (len .Values.alfred.tenants) 1}}
                {{- range $index, $tenant := .Values.alfred.tenants }}
                {{ toJson . }}{{- if ne $index $lastIndex -}}, {{ end }}
                {{- end }}
            ],
            "federation": {
                "endpoints": [
                    "https://www.wu2-ppe.prague.office-int.com",
                    "https://www.wu2.prague.office-int.com",
                    "https://www.eu2.prague.office-int.com",
                    "https://www.we.prague.office-int.com"
                ]
            },
            "auth": {
                "endpoint": "http://{{ template "riddler.fullname" . }}"
            }
        },
        "login": {
            "enabled": true,
            "microsoft": {
                "clientId": "{{ .Values.login.microsoft.clientId }}",
                "secret": "{{ .Values.login.microsoft.secret }}"
            },
            "accounts": [
                {
                    "username": "{{ .Values.login.accounts.username }}",
                    "password": "{{ .Values.login.accounts.password }}"
                }
            ]
        },
        "redis": {
            "host": "{{ .Values.redis.url }}",
            "port": 6379
        },
        "error": {
            "track": true,
            "endpoint" : "{{ .Values.error.endpoint }}"
        },
        "worker": {
            "intelligence": {
                "textAnalytics": {
                    "key": "{{ .Values.worker.intelligence.textAnalytics.key }}"
                },
                "translation": {
                    "key": "{{ .Values.worker.intelligence.translation.key }}"
                },
                "pinpointEditor": {
                    "key": "{{ .Values.worker.intelligence.pinpointEditor.key }}"
                }
            },
            "alfredUrl": "http://{{ template "alfred.fullname" . }}",
            "gatewayUrl": "http://{{ template "gateway.fullname" . }}",
            "serverUrl": "{{ .Values.alfred.externalUrl }}",
            "blobStorageUrl": "{{ .Values.historian.externalUrl }}",
            "repository": "prague",
            "clusterNpm": "{{ .Values.worker.clusterNpm }}",
            "npm": "{{ .Values.worker.npm }}",
            "permission": ["snapshot", "spell", "intel", "translation", "chain-snapshot", "chain-spell", "chain-intel", "chain-translation"]
        },
        "keyValue": {
            "documentUrl": "https://www.wu2.prague.office-int.com/loader/prague/kv-cache-0000"
        },
        "express": {
            "session": {
                "secret": "{{ .Values.express.session.secret }}"
            }
        }
    }
