name: "Auto Assign Pull Request"
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main
    - release/*

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: open-telemetry/assign-reviewers-action@main
      with:
        config-file: '.github/code_owners.yml'
        # repo-token: ${{ secrets.GITHUB_TOKEN }}
        assign-users: false
        request-user-reviews: false
