name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - docs/hugo
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - docs/hugo
  repository_dispatch:
    # all types
  workflow_dispatch:
    # all types

jobs:
  build_and_deploy_job:
    if: github.event_name == 'repository_dispatch' # || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: Download and extract api-extractor JSON
        id: docs-json
        run: |
          wget -q https://fluidframework.z19.web.core.windows.net/${{ github.sha }}.tar.gz -O api-extractor.tar.gz
          if [ $? -ne 0 ]; then
            wget -q https://fluidframework.z19.web.core.windows.net/latest.tar.gz -O api-extractor.tar.gz
            echo "${{ github.sha }}.tar.gz not found; downloading latest.tar.gz"
          fi
          mkdir -p ./_api-extractor-temp/doc-models/
          tar -C ./_api-extractor-temp/doc-models/ -zxvf api-extractor.tar.gz
      - name: npm run build:mdapidocs
        id: mdapidocs
        run: |
          npm run build:mdapidocs
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        env:
          HUGO_BASEURL: https://polite-pebble-004dbbb10.azurestaticapps.net
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_PEBBLE_004DBBB10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/docs" # App source code path
          # api_location: "api" # Api source code path - optional
          app_artifact_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_PEBBLE_004DBBB10 }}
          action: "close"
