name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  paths_label:
    runs-on: ubuntu-latest
    name: Label based on file paths
    steps:
      - uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4 # ratchet:actions/labeler@v4.0.2
        with:
          configuration-path: ".github/actions-labeler.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true # add/remove labels as modified paths in the PR change
  branches_label:
    runs-on: ubuntu-latest
    name: Label base branches and external contributors
    steps:
      - uses: srvaroa/labeler@v1.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
