name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  paths_label:
    runs-on: ubuntu-latest
    name: Label based on file paths
    steps:
      - uses: actions/labeler@26546f6c4d63b6c0623e8e39bde7869e3c2b1d7b # pin@v3
        with:
          configuration-path: ".github/actions-labeler.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true # add/remove labels as modified paths in the PR change
  branches_label:
    runs-on: ubuntu-latest
    name: Label base branches
    steps:
      - uses: srvaroa/labeler@cc2f468623534d06a41e5dc591e9b6a1355a5e7b # pin@main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  external_label:
    runs-on: ubuntu-latest
    name: Label external PRs
    steps:
      - uses: tylerbutler/labelmaker-action@4d05a42cd2272689037a1cd82b7ad0e36aaddb23 # pin@main
        with:
          token: "${{ secrets.ORG_TOKEN }}"
