name: Release branch warning
on:
  pull_request_target:
    types:
      - opened

      # This is triggered when the base branch changes; handles the case where you open a PR against main then change the
      # base branch to a release branch.
      - edited
    branches:
      - release/client/**
      - release/server/**
      - test/release/**

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  warning:
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    steps:
      # release notes: https://github.com/actions/checkout/releases/tag/v6.0.0
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
          submodules: false

      - name: Post warning in comment
        # release notes: https://github.com/marocchino/sticky-pull-request-comment/releases/tag/v2.9.4
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # ratchet:marocchino/sticky-pull-request-comment@v2
        with:
          header: release-warning
          path: ${{ github.workspace }}/.github/workflows/data/release-branch-warning.md
          only_create: true
