name: "Fluid PR Validation"
on:
  pull_request:
    types:
      - opened # PR is created
      - synchronize # commits added to PR
      - reopened # closed PR re-opened
      - edited # title or body edited, or base branch changed
    branches:
      - main
      - next
      - release/*

jobs:
  # This job determines what paths have changed in the PR and outputs a boolean. Using the paths filter in the
  # pull_request event doesn't work. Per the GitHub docs, "If a workflow is skipped due to path filtering, branch
  # filtering or a commit message, then checks associated with that workflow will remain in a 'Pending' state. A pull
  # request that requires those checks to be successful will be blocked from merging." This means we can't make such
  # jobs required for PRs to be merged, because the jobs just stay in the pending state.
  changed-paths:
    name: Determine changed paths
    runs-on: ubuntu-latest
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # ratchet:dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            build-tools:
              - 'build-tools/**'
              - '.github/workflows/pr-validation.yml'
    # Set job outputs to values from filter step
    outputs:
      build-tools: ${{ steps.filter.outputs.build-tools }}

  validate-codeowners:
    name: Validate CODEOWNERS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
        with:
          persist-credentials: false
      - uses: mszostok/codeowners-validator@7f3f5e28c6d7b8dfae5731e54ce2272ca384592f # ratchet:mszostok/codeowners-validator@v0.7.4
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
          checks: "files,duppatterns,syntax"

  # This job checks that PR template placeholder content has been removed from the PR body.
  placeholder-content:
    name: PR template placeholder content
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'edited' ||
      github.event.action == 'opened' ||
      github.event.action == 'reopened'
    steps:
      - uses: sitezen/pr-comment-checker@f1e956fac00c6d1163d15841886ae80b7ae58ecb # ratchet:sitezen/pr-comment-checker@v1.0.1
        with:
          pr_description_should_not_contain: |
            Feel free to remove or alter parts of this template that do not offer value for your specific change
          wrong_pr_description_message: |
            Your PR description contains placeholder content from the PR template. Remove or replace the placeholder
            content. More information at:
            https://github.com/microsoft/FluidFramework/wiki/Commit-message-style#pr-template-content
