name: Website validation
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"
      - "*.md"
      - "**/*.md"
      - "!.changeset/**"
      - "!build-tools/**"
      - "!RELEASE_NOTES/**"
      - "!server/**"

defaults:
  run:
    working-directory: ./docs

permissions:
  contents: read

jobs:

  # Build the website (including API documentation).
  # Publish the build artifact for subsequent jobs to leverage.
  build_site:
    runs-on: ubuntu-latest
    name: Build site
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ratchet:actions/checkout@v4
        with:
          submodules: false
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # ratchet:pnpm/action-setup@v4
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: docs/pnpm-lock.yaml
      - name: Build site artifact
        run: |
          pnpm i --frozen-lockfile
          npm run build
      - name: Validate CSP hashes
        run: |
          ./validateHashes.sh
      - name: Upload site artifact
        # release notes: https://github.com/actions/upload-artifact/releases/tag/v5.0.0
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # ratchet:actions/upload-artifact@v5
        with:
          name: fluidframework-site
          path: docs/build
          retention-days: 3

  # Run linter checks against the website content and infrastructure.
  lint:
    runs-on: ubuntu-latest
    name: pnpm lint
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ratchet:actions/checkout@v4
        with:
          submodules: false
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # ratchet:pnpm/action-setup@v4
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: docs/pnpm-lock.yaml
      - name: pnpm lint
        run: |
          pnpm i --frozen-lockfile
          pnpm lint

  # Run the website's tests.
  test:
    runs-on: ubuntu-latest
    name: ðŸ§ª Website Tests
    needs: build_site
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
        with:
          submodules: false
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # ratchet:pnpm/action-setup@v4
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: Download site artifact
        # release notes: https://github.com/actions/download-artifact/releases/tag/v4.1.8
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
        with:
          name: fluidframework-site
          path: docs/build
      - name: Install dependencies
        run: "pnpm i --frozen-lockfile"
      - name: Run tests
        run: "npm run test"

  # Run the link checker against the website.
  # Publish the results to the PR as a comment.
  broken_link_check:
    runs-on: ubuntu-latest
    name: ðŸ”— Broken Link Check
    needs: build_site
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
        with:
          submodules: false
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # ratchet:pnpm/action-setup@v4
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # ratchet:actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: docs/pnpm-lock.yaml
      - name: Create results folder
        run: mkdir -p ./results

      - name: Download site artifact
        # release notes: https://github.com/actions/download-artifact/releases/tag/v4.1.8
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
        with:
          name: fluidframework-site
          path: docs/build
      - name: Install dependencies
        run: "pnpm i --frozen-lockfile"
      - name: Check for broken links
        id: linkcheck
        continue-on-error: true
        run: |
          set -o pipefail
          pnpm run ci:check-links | tee ./results/linkcheck-output.txt

      - name: Save PR number
        run: echo ${{ github.event.number }} > ./results/pr
      - name: Save linkcheck report
        run: |
          cat "$GITHUB_WORKSPACE/.github/workflows/data/linkcheck-${{ steps.linkcheck.outcome }}.md" | tee ./results/linkcheck
          echo -e "\n#### linkcheck output\n\n\`\`\`" | tee -a ./results/linkcheck
          cat ./results/linkcheck-output.txt | tee -a ./results/linkcheck
          echo -e "\n\`\`\`" | tee -a ./results/linkcheck
      - name: Upload results artifact
        # release notes: https://github.com/actions/upload-artifact/releases/tag/v5.0.0
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # ratchet:actions/upload-artifact@v5
        with:
          name: website-validation-results
          path: ./docs/results
          retention-days: 3
